
function menudata() {
    const menuFood = [
        {
            category:"Starter",
            dish:"Edamame",
            price:"6",
            ingredient:"soybeans",
        },
        {
            category:"Starter",
            dish:"Yasai Tempura",
            price:"9",
            ingredient:"Vegetables",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
        {
            category:"",
            dish:"",
            price:"",
            ingredient:"",
        },
    ]
}

export default menudata